Repository sul-dlss/common-accessioning, pull requests merged in 2019-08, with the labels that each got.

#338 Use the workspace cleanup API in dor-services-app
  Gemfile
  Gemfile.lock
  lib/cleanup_reset_service.rb
  lib/robots/dor_repo/dissemination/cleanup.rb
  spec/lib/cleanup_reset_service_spec.rb
  spec/robots/dissemination/cleanup_spec.rb
Labels: tech debt

#366 allow 3d content type to pass through from stub content metadata
  lib/dor/assembly/stub_content_metadata_parser.rb
  spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
Labels: 3d obj, SDR Fall 2019

#378 raise error and/or notify Honeybadger and log error if a fedora save doesn't work.
  lib/datastream_builder.rb
  lib/robots/dor_repo/accession/embargo_release.rb
  lib/robots/dor_repo/etd_submit/check_marc.rb
  lib/technical_metadata_service.rb
  spec/lib/datastream_builder_spec.rb
  spec/lib/technical_metadata_service_spec.rb
  spec/robots/accession/embargo_release_spec.rb
  spec/robots/etd_submit/check_marc_spec.rb
Labels: SDR Fall 2019, tech debt
